name = "innobeweeglab"
compatibility_date = "2024-11-06"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "innobeweeglab"
database_id = "7dc100dc-087a-43b8-8746-2008ad985062"
