import type { Finding, Project, Report, Triangulation } from "../shared/types";

const escapeHtml = (s: string) =>
  s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");

export function toMarkdown(
  project: Project, report: Report, findings: Finding[], triangulations: Triangulation[],
): string {
  const label = new Map<string, string>([
    ...findings.map((f) => [f.id, `${f.perspective} · ${f.dimension} · ${f.statement}`] as [string, string]),
    ...triangulations.map((t) => [t.id, `${t.convergence} · ${t.dimension} · ${t.title}`] as [string, string]),
  ]);

  const head = [
    `# ${report.title}`,
    "",
    [project.municipality, project.neighbourhood, project.period].filter(Boolean).join(" · "),
    project.research_question ? `\n**Research question.** ${project.research_question}` : "",
    "",
    `*Draft generated by the InnoBeweegLab Evidence Engine (${report.engine}) on ` +
    `${new Date(report.updated_at).toLocaleDateString("en-GB")}. ` +
    `Status: ${report.status}. Every section below is a draft for researcher validation.*`,
    "",
    "---",
  ].filter(Boolean).join("\n");

  const body = report.sections.map((s) => {
    const references = s.citations.length
      ? `\n\n<details><summary>Source references (${s.citations.length})</summary>\n\n` +
        s.citations.map((c) =>
          `- \`${c.evidence_id}\` — ${c.label}${label.has(c.evidence_id) ? `\n  ${label.get(c.evidence_id)}` : ""}` +
          `\n  > "${c.cited_text}"`).join("\n") +
        "\n\n</details>"
      : "";
    const flag = s.status === "approved" ? "" : `\n\n*[${s.status} — not yet approved by a researcher]*`;
    return `## ${s.title}\n\n${s.body_md || "_(empty)_"}${flag}${references}`;
  }).join("\n\n");

  const appendix = [
    "---",
    "",
    "## Appendix — evidence store",
    "",
    "| Id | Perspective | Dimension | Direction | Strength | n | Statement |",
    "| --- | --- | --- | --- | --- | --- | --- |",
    ...findings.map((f) =>
      `| \`${f.id}\` | ${f.perspective} | ${f.dimension} | ${f.direction} | ${f.strength} | ${f.support_n} | ${f.statement.replace(/\|/g, "\\|")} |`),
  ].join("\n");

  return `${head}\n\n${body}\n\n${appendix}\n`;
}

export function toHtml(
  project: Project, report: Report, findings: Finding[], triangulations: Triangulation[],
): string {
  const markdown = toMarkdown(project, report, findings, triangulations);
  return `<!doctype html>
<html lang="nl"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${escapeHtml(report.title)}</title>
<style>
  :root { color-scheme: light; }
  body { font: 16px/1.65 "Inter", ui-sans-serif, system-ui, -apple-system, sans-serif;
         max-width: 46rem; margin: 0 auto; padding: 3rem 1.5rem 6rem;
         color: #14201c; background: #fbfaf7; }
  h1 { font-size: 2rem; letter-spacing: -0.02em; margin: 0 0 .25rem; }
  h2 { font-size: 1.3rem; margin: 2.5rem 0 .6rem; padding-top: 1.25rem; border-top: 1px solid #dfe5e1; }
  h3 { font-size: 1.05rem; margin: 1.75rem 0 .4rem; }
  p { margin: 0 0 .9em; }
  ul, ol { padding-left: 1.25em; margin: 0 0 .9em; }
  li { margin-bottom: .25em; }
  blockquote { margin: 1rem 0; padding: .5rem 0 .5rem 1rem; border-left: 3px solid #117a5e;
               color: #3c4a45; font-style: italic; }
  table { border-collapse: collapse; width: 100%; font-size: .85rem; margin: 1rem 0; }
  th, td { border: 1px solid #dfe5e1; padding: .4rem .55rem; text-align: left; vertical-align: top; }
  th { background: #eef3f0; }
  code { background: #eef3f0; padding: .1rem .3rem; border-radius: 3px;
         font-family: ui-monospace, SFMono-Regular, Menlo, monospace; font-size: .85em; }
  details { margin: 1rem 0; font-size: .9rem; background: #f2f5f3; border-radius: 8px; padding: .75rem 1rem; }
  summary { cursor: pointer; font-weight: 600; }
  em { color: #5a6a64; }
  hr { border: none; border-top: 1px solid #dfe5e1; margin: 1.5em 0; }
  @media print { body { background: #fff; padding-top: 1rem; }
                 details { break-inside: avoid; } details[open] summary { list-style: none; } }
</style></head>
<body>
${renderMarkdown(markdown)}
</body></html>`;
}

/**
 * Server-side Markdown rendering for the export, over the same subset `toMarkdown`
 * emits. Rendering here rather than shipping a script keeps the exported file a
 * self-contained document that prints, converts and archives without JavaScript.
 */
function renderMarkdown(markdown: string): string {
  const out: string[] = [];
  let list: string[] = [];
  let table: string[][] = [];
  let quote: string[] = [];

  const flushList = () => {
    if (!list.length) return;
    out.push(`<ul>${list.map((i) => `<li>${inlineHtml(i)}</li>`).join("")}</ul>`);
    list = [];
  };
  const flushQuote = () => {
    if (!quote.length) return;
    out.push(`<blockquote>${quote.map(inlineHtml).join("<br>")}</blockquote>`);
    quote = [];
  };
  const flushTable = () => {
    if (!table.length) return;
    const [head, ...body] = table;
    out.push(
      `<table><thead><tr>${head.map((c) => `<th>${inlineHtml(c)}</th>`).join("")}</tr></thead>` +
      `<tbody>${body.map((r) => `<tr>${r.map((c) => `<td>${inlineHtml(c)}</td>`).join("")}</tr>`).join("")}</tbody></table>`,
    );
    table = [];
  };

  for (const raw of markdown.split("\n")) {
    const line = raw.trimEnd();

    // The reference blocks are already HTML; pass them through untouched.
    if (/^<\/?(details|summary)/.test(line)) {
      flushList(); flushQuote(); flushTable();
      out.push(line);
      continue;
    }
    if (/^\s*\|.*\|\s*$/.test(line)) {
      flushList(); flushQuote();
      const cells = line.trim().slice(1, -1).split("|").map((c) => c.trim());
      if (!/^[-: ]+$/.test(cells.join(""))) table.push(cells);
      continue;
    }
    flushTable();

    if (/^\s{2,}>/.test(line)) { list.push(`<em>${inlineHtml(line.replace(/^\s*>\s?/, ""))}</em>`); continue; }
    if (/^\s*[-*]\s+/.test(line)) { flushQuote(); list.push(line.replace(/^\s*[-*]\s+/, "")); continue; }
    if (/^\s{2,}\S/.test(line) && list.length) { list[list.length - 1] += `<br>${inlineHtml(line.trim())}`; continue; }
    flushList();

    if (/^>\s?/.test(line)) { quote.push(line.replace(/^>\s?/, "")); continue; }
    flushQuote();

    if (!line.trim()) continue;
    if (/^###\s+/.test(line)) out.push(`<h3>${inlineHtml(line.slice(4))}</h3>`);
    else if (/^##\s+/.test(line)) out.push(`<h2>${inlineHtml(line.slice(3))}</h2>`);
    else if (/^#\s+/.test(line)) out.push(`<h1>${inlineHtml(line.slice(2))}</h1>`);
    else if (/^(---|\*\*\*)\s*$/.test(line)) out.push("<hr>");
    else out.push(`<p>${inlineHtml(line)}</p>`);
  }
  flushList(); flushQuote(); flushTable();
  return out.join("\n");
}

function inlineHtml(text: string): string {
  // Pre-rendered fragments (list continuation lines) already carry markup.
  const parts = text.split(/(<br>|<em>.*?<\/em>)/g);
  return parts.map((part) => {
    if (/^(<br>|<em>)/.test(part)) return part;
    return escapeHtml(part)
      .replace(/`([^`]+)`/g, "<code>$1</code>")
      .replace(/\*\*([^*]+)\*\*/g, "<strong>$1</strong>")
      .replace(/\*([^*]+)\*/g, "<em>$1</em>")
      .replace(/(^|[^A-Za-z0-9_])_([^_]+)_(?![A-Za-z0-9_])/g, "$1<em>$2</em>");
  }).join("");
}
